CREATE TABLE public.telecom (
	customerID VARCHAR,
	gender VARCHAR,
	SeniorCitizen BIT,
	Partner VARCHAR,
	Dependents VARCHAR,
	tenure INT,
	PhoneService VARCHAR,
	MultipleLines VARCHAR,
	InternetService VARCHAR,
	OnlineSecurity VARCHAR,
	OnlineBackup VARCHAR,
	DeviceProtection VARCHAR,
	TechSupport VARCHAR,
	StreamingTV VARCHAR,
	StreamingMovies VARCHAR,
	Contract VARCHAR,
	PaperlessBilling VARCHAR,
	PaymentMethod VARCHAR,
	MonthlyCharges DECIMAL,
	TotalCharges DECIMAL,
	Churn VARCHAR
);